STORIS/eslint-config

- CHANGELOG.md
- package-lock.json
- package.json
- react.js
This change enables `jsx-a11y/recommended` in the react rules and prepares for a release 0.0.2.
> Enable jsx-a11y/recommended in react rules

- CHANGELOG.md
The order of comparison was incorrect in the changelog.  This corrects the changelog so the links compare properly.
> Fix changelog so compare works properly

- CHANGELOG.md
- package.json
- react.js
This PR disables the `react/react-in-jsx-scope` rule since when using the new JSX transform for React 17+, importing React is no longer a requirement, provided that the transform is being used.
> Disable react/react-in-jsx-scope rule

- CHANGELOG.md
- package-lock.json
- package.json
This PR prepares for 0.0.3 release by bumping the version and updating the CHANGELOG.
> Prepare for 0.0.3 release

- lib/shared.js
This PR enables the `@typescript-eslint/consistent-type-exports` rule in all configurations.  It uses the `fixMixedExportsWithInlineTypeSpecifier` to allow for mixed type and regular exports to be autofixed inline.
> Enable consistent-type-exports rule

- CHANGELOG.md
- package-lock.json
- package.json
This PR prepares for 0.0.4 release by bumping the version and updating the CHANGELOG.
> Prepare for release 0.0.4

- lib/shared.js
- react.js
This PR removes the override disabling `@typescript-eslint/no-unused-vars` as there was a mixup between the behavior of that and the `no-undef` rule.  Additionally, it extends `plugin:react/jsx-runtime` in the react configuration to ensure that when React is imported when it does not need to be an error is trigger for `no-unused-vars`.
> Better handling of no-unused-vars

- lib/shared.js
- node.js
Currently the `no-restricted-syntax` override to allow "for of" expressions was enabled for node but not react.  This change moves the rule from `node` to `shared` so it will be enabled for both node and react.
> Relocate no-restricted-syntax from node to shared

- CHANGELOG.md
- package-lock.json
- package.json
This PR prepares for 0.0.6 release by bumping the version and updating the CHANGELOG.
> Prepare for release 0.0.6

- lib/shared.js
The `pathGroups` setting in the eslint config is unnecessary.  `eslint-plugin-import` will treat import paths that are not relative, node built-ins, or from `node_modules` as  `internal`.  The sequence of the existing `groups` ensures that the internal group is already in the right place, and the alphabetizing of imports ensures the proper sequence within the group.  Essentially this configuration is doing nothing currently and can be dropped.
> Eliminate pathgroup

- lib/shared.js
- node.js
This PR adds an override that excludes `prefer-default-export` from `constants.ts` files.
> Add an override to exclude prefer-default-export from constants.ts

- CHANGELOG.md
- package-lock.json
- package.json
This PR prepares for 0.0.8 release by bumping the version and updating the CHANGELOG.
> Prepare for 0.0.8

- lib/shared.js
In the shared configuration there are two override blocks to prefer named exports and nothing more.  To avoid duplication, this PR consolidates those overrides into a single block.
> Consolidate named exports overrides in shared

- .editorconfig
Add `cjs` and `mjs` overrides to editorconfig to ensure use of tabs.
> Add cjs and mjs to editorconfig

- nodejs.js
This PR updates the `nodejs` rule set to activate the [explicit-module-boundary-types](https://typescript-eslint.io/rules/explicit-module-boundary-types) rule to ensure that the external facing API of modules has return types.
> Add explicit-module-boundary-types rule to nodejs set

- nodejs.js
When working in a mixed js/ts codebase, the `explicit-module-boundary-types` error was being triggered on `js` files.  This changes the `nodejs` configuration so that error will only be triggered on `ts` files.
> Only use explicit-module-boundary-types on ts files

- CHANGELOG.md
- package-lock.json
- package.json
This PR prepares for 1.0.0 release by bumping the version and updating the CHANGELOG.
> Prepare for 1.0.0

- lib/shared.js
The @typescript-eslint rules which require type checking do not work very well in pure `js` files.  This PR changes it so those rules are only activated in `ts` and `tsx` files.
> Better support for js files

- CHANGELOG.md
- package-lock.json
- package.json
This PR prepares for 1.0.1 release by bumping the version and updating the CHANGELOG.
> Prepare for release 1.0.1

- README.md
- lib/shared.js
- package-lock.json
- package.json
- react.js
This PR adds `eslint-plugin-testing-library` to the react configuration and requires it as a peer dependency.  The plugin has been added to an override that targets tests only, [as described in the project's readme](https://github.com/testing-library/eslint-plugin-testing-library#run-the-plugin-only-against-test-files).
Applied the regex recommended by the testing-library eslint rule's docs (which is based on [Jest's defaults](https://jestjs.io/docs/configuration#testmatch-arraystring)) to the shared config.  To do this, I've split its override in two: a general override covering JavaScript and TypeScript test suites and another that is specific to TypeScript.
> Add `eslint-plugin-testing-library` to React configuration

- package.json
eslint-plugin-testing-library should have been included in `peerDependenciesMeta` as an optional peer dependency when it was introduced in #92
> Optional peer dependency: eslint-plugin-testing-library 

- package-lock.json
- package.json
This PR updates to the latest version of `eslint-config-airbnb-typescript` which contains a breaking change for supported peer dependency ranges on `@typescript-eslint`.  To accommodate for that, the peer dependency range for `@typescript-eslint` needed to be bumped as well.  Since multiple peer dependency ranges are being bumped, I've also bumped every other peer dependency range to the latest semver minor.
> Update eslint-config-airbnb-typescript and all peer dependency ranges

- README.md
- package-lock.json
- package.json
`jest` is unnecessary as a peer dependency.  Eliminating it will reduce the likelihood of merge conflicts due to changing jest revisions in the future.  Although to use `eslint-plugin-jest` you'd likely require `jest`, its not a definite requirement.
> Eliminate jest as peer dependency

- CHANGELOG.md
- package-lock.json
- package.json
This PR updates the version to 3.1.0 and updates the CHANGELOG to reflect the changes.
> Prepare for release 3.1.0

- .circleci/config.yml
- package.json
This PR augments the `engines` property of `package.json` to support `^18.0.0` as well as `^16.0.0`.  The CI configuration was adjusted to run tests against both `16.15.0` and `18.0.0`.  Note: The circle [tags](https://circleci.com/developer/images/image/cimg/node) don't appear to have been updated to support `18.1.0` yet.
> Update support for Node 18

- CHANGELOG.md
- package-lock.json
- package.json
This PR updates the version to 3.2.0 and updates the CHANGELOG to reflect the changes.
> Prepare for version 3.2.0
